Project review
samuelmoiwa/Project-review-from-trials pull request #1
Opened 2022-08-21 01:57 UTC by samuelmoiwa

## PROJECT REVIEW

## Solution description

***CSS:*** Check for code correctness in the CSS style files
***HTML*** Check the Html code for HTML semantic tags, and code correctness

## Address affected and ensured
* HTML file
* CSS file
---

2022-08-21 03:10 UTC, samuelmoiwa commented on index.html
> +  <body>
I think the code will look nicer and more readable if the unnecessary white spaces are removed 😊.

2022-08-21 03:10 UTC, samuelmoiwa commented on style.css
> +#hero > h2 {
I think it'll be more professional to use class(.) for CSS selector properties than to use ID(#)👌

2022-08-21 03:10 UTC, samuelmoiwa commented on index.html
> +    </footer>
I think it'll be best practice to put all HTML tags, including the footer tag, inside the main body tag of the code. 👌 It makes the web page more informative and adaptable, allowing browsers and search engines to better interpret content.

2022-08-22 09:54 UTC, Kossi-stack requested changes
## Hi @,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

 - [ ] Kindly edit the PR's title to something more descriptive. it can be "Hello Microverse Project PR or Hello Microverse Project".
 - [ ] Please make sure to use [this readme template](https://github.com/microverseinc/readme-template/blob/master/README.md) and please be sure to edit all of the sections to better suit your project.
- [ ] Kindly make sure to use [these linters](https://github.com/microverseinc/linters-config/tree/master/html-css) provided by Microverse and make sure they are set up correctly and they all pass with green checkmarks.
 - [ ] Kindly add a descriptive pull request message, This helps other programmers who want to take a look at your code to understand what changes you made to a particular branch, you can find an example [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#5-basic-rules-to-follow-in-microverse-projects).
 - [ ] Kindly capitalize the first letter of your commit message in the next milestone so it looks professional.

 _Check the comments under the review for more changes_.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-08-22 11:22 UTC, samuelmoiwa commented on index.html
> +<!DOCTYPE html>
![](https://c.tenor.com/0Q8SiDHvSZIAAAAC/so-close-so-close-seth-meyers.giff)

The work is looking perfect so far.
I think there are a few key configurations you are still missing.
In other for this project to follow the proper git flow, I think you need to set up a few files.

-  add **.gitignore** to your project
-  **Linters**  [ link to the linters life, find setup instructions](https://github.com/microverseinc/linters-config)

2022-08-22 11:31 UTC, Qoosim approved these changes
## **Status: Approved** :tada: 

Hi @samuelmoiwa, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

-  Descriptive pull request message. :heavy_check_mark: 
-  Professional Documentation of work. :heavy_check_mark: 
-  Professional README file. :heavy_check_mark: 
-  Meaningful commit messages. :heavy_check_mark: 


![Got](https://camo.githubusercontent.com/aa9137eba4285ba68320a19592e5e655279c09be5c8fc2fb7ef499d61cf26010/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f3855475651455370444d4d516c37796433462f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-22 12:07 UTC, merged